name: Pull Request Check

on:
  pull_request:
    branches:
      - 'release/v2.12.0'
  push:
    branches:
      - 'release/v2.12.0'
      
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0
    
    - name: Build project
      run: dotnet build HunterPie --nologo -v q --property WarningLevel=0 /clp:ErrorsOnly

    - name: Run unit tests
      run: dotnet test *.Tests

    - name: Run formatter
      run: dotnet format --verify-no-changes

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          **/*
